// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA80RMdkuj0DD9brrOrqOsw28musUZ8HTM',
    appId: '1:25897056775:web:14ecf70d8b02bb70cc88a2',
    messagingSenderId: '25897056775',
    projectId: 'checkga-1f192',
    authDomain: 'checkga-1f192.firebaseapp.com',
    storageBucket: 'checkga-1f192.firebasestorage.app',
    measurementId: 'G-1WM50YKVKW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAql8bR2g6SV-JN-lZSFwzwjRR7sKaO8gg',
    appId: '1:25897056775:android:7e72230397468955cc88a2',
    messagingSenderId: '25897056775',
    projectId: 'checkga-1f192',
    storageBucket: 'checkga-1f192.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSzUBpL_hvvcyzxIsXPQpufBRvnHGpyAw',
    appId: '1:25897056775:ios:f89dd9c6b7f377b5cc88a2',
    messagingSenderId: '25897056775',
    projectId: 'checkga-1f192',
    storageBucket: 'checkga-1f192.firebasestorage.app',
    iosBundleId: 'com.checkga.app.checkga',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSzUBpL_hvvcyzxIsXPQpufBRvnHGpyAw',
    appId: '1:25897056775:ios:f89dd9c6b7f377b5cc88a2',
    messagingSenderId: '25897056775',
    projectId: 'checkga-1f192',
    storageBucket: 'checkga-1f192.firebasestorage.app',
    iosBundleId: 'com.checkga.app.checkga',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA80RMdkuj0DD9brrOrqOsw28musUZ8HTM',
    appId: '1:25897056775:web:c4028e3d6bdabdc9cc88a2',
    messagingSenderId: '25897056775',
    projectId: 'checkga-1f192',
    authDomain: 'checkga-1f192.firebaseapp.com',
    storageBucket: 'checkga-1f192.firebasestorage.app',
    measurementId: 'G-1ZTE4VZ56Z',
  );

}